#!/usr/bin/env python3
"""generate.py: writes testdata/fixture-many/init-many, the many-records
fixture initiative (docs/specs/leftovers-6.md FR-7, S3). Deterministic: run
it again and the tree is the same, so the committed copy is its output.

76 decision records: 3 waiting, 70 ruled, 2 superseded and 1 withdrawn.
"nightly" is in one ruled record (0012) and one superseded (0040), so a find
for it reads `Timeline · 1 of 73 · 1 more among 3 hidden` (N4). Raised from
20 Jul 2026, under 90 days to today (4 Oct), so the Decisions Timeline is
weekly at Fit (N3's ticks). Milestones: three on 18 Aug and four on 22 Sep
(N3's titles). Cards are all `next`, none open-ended, and m-timed's branch
carries times (scripts/fixture-home.sh commits it on 30 Sep), so Cards
offers Hours and, with today in view, has no card in the window (N5).

    python3 testdata/fixture-many/generate.py
"""
import datetime as dt
import os
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "init-many")
START = dt.date(2026, 7, 20)
TODAY = dt.date(2026, 10, 4)

TOPICS = [
    "where the scan runs", "who reviews a wave", "the board's default view", "how cards name their seat",
    "the cache's lifetime", "which machine owns the order", "the rail's groups", "how stages end",
    "the sync interval", "what a gate must say", "the review build's bundle", "nightly scan on the build box",
    "the agents feed's period", "how long a seat may idle", "the retire default", "the help document",
    "the decision record's shape", "how a ruling is signed", "the find field's words", "the calendar's first day",
    "the roadmap's appetite", "who may rule", "what Needs me counts", "the badge's number",
    "the old initiative's archive", "the crew model", "the statusline install", "the doctor's checks",
    "a card's due date", "the milestone format", "the target's meaning", "the done column's cap",
    "the overview tiles", "the conversations list", "the mailbox's health words", "the capped seat",
    "the deaf seat", "the wake count", "the branch convention", "nightly export to the archive",
    "the runs baseline", "the cost column", "the context fill", "the prelude file",
    "the prompt file", "the probe family", "the session name ceiling", "the socket directory",
    "the keychain item", "the passcode cooldown", "the auth mode", "the Firestore database",
    "the snapshot payload", "the merge rule", "the local-wins rule", "the remote machines",
    "the window's minimum size", "the top bar's crumbs", "the settings screen", "the rail's width",
    "the collapsed rail", "the rank numbers", "the group headers", "the drag library",
    "the card back", "the comments feed", "the notes' signature", "the Done column",
    "the stage stepper", "the decisions chip", "the record body", "the timeline rows",
    "the zoom levels", "the edge pointers", "the today line", "the weekend tint",
]

SUPERSEDED = {10: 11, 40: 41}   # superseded record -> the one that supersedes it
WITHDRAWN = {25}
WAITING = {74: dt.date(2026, 9, 28), 75: dt.date(2026, 10, 1), 76: dt.date(2026, 10, 3)}


def record(n):
    topic = TOPICS[n - 1]
    title = topic[0].upper() + topic[1:]
    raised = WAITING.get(n) or START + dt.timedelta(days=(n - 1) * 70 // 73)
    ruled = None if n in WAITING or n in WITHDRAWN else min(raised + dt.timedelta(days=(n * 7) % 5), TODAY - dt.timedelta(days=1))
    status = "proposed" if n in WAITING else "withdrawn" if n in WITHDRAWN else "superseded" if n in SUPERSEDED else "ruled"
    options = ["keep it as it is", "change it"]
    chosen = options[n % 2] if ruled else ""
    supersedes = [f"{k:04d}" for k, v in SUPERSEDED.items() if v == n]
    fm = [
        "---",
        f"title: {title}",
        f"status: {status}",
        f"raised: {raised.isoformat()}",
        "raised_by: fse",
        f"owner: {'pablo' if n % 3 else 'ana'}",
        f"ruled: {ruled.isoformat() if ruled else ''}",
        f"ruled_by: {'pablo' if ruled else ''}",
        f"options: [{', '.join(options)}]",
        f"chosen: {chosen}",
        "cards: []",
        "threads: []",
        f"supersedes: [{', '.join(supersedes)}]",
        f"superseded_by: {SUPERSEDED[n]:04d}" if n in SUPERSEDED else "superseded_by:",
        "---",
        "",
        "## Question",
        "",
        f"What does the fixture initiative decide about {topic}? Record {n:04d} of the many-records fixture.",
        "",
    ]
    if ruled:
        fm += ["## Ruling", "", f"pablo, {ruled.isoformat()}: \"{chosen}\".", ""]
    slug = topic.replace("'", "").replace(" ", "-").lower()
    return f"{n:04d}-{slug}.md", "\n".join(fm)


INITIATIVE = """\
id: init-many
title: Initiative Many
client: acme
status: active
started: 2026-07-15
machine: testbox
description: The many-records fixture, generated by testdata/fixture-many/generate.py.
goal: Initiative Many keeps 76 decisions findable
measure: any ruling is found by number or words in one try
repos:
  - app
ports_to: none
target: 2026-10-30
milestones:
  - date: 2026-08-18
    title: Schema frozen
  - date: 2026-08-18
    title: API review held
  - date: 2026-08-18
    title: Load test passed
  - date: 2026-09-22
    title: Pilot opens
  - date: 2026-09-22
    title: Docs published
  - date: 2026-09-22
    title: Support trained
  - date: 2026-09-22
    title: Billing switched on
"""

ROADMAP = """\
stages:
  - id: discover
    title: Discover
    outcome: the records say what the operator needs
    exit: [the find covers number and words]
    appetite: two waves
    done: 2026-08-15
  - id: build
    title: Build
    outcome: the view holds seventy records
    exit: [N4 passes]
    appetite: three waves
    target: 2026-10-20
  - id: ship
    title: Ship
    outcome: the operator rules from it every day
    exit: [a week of rulings]
    appetite: one wave
"""

CARDS = {
    "m-timed": """\
---
title: A branch with times of day
status: next
repos: [app]
branch: feat/timed
updated: 2026-09-30
next: "Review the timed branch"
stage: build
---
""",
    "m-pilot": """\
---
title: Pilot with acme
status: next
repos: [app]
branch: none
start: 2026-08-10
due: 2026-09-25
updated: 2026-09-20
next: "Close the pilot"
stage: build
---
""",
    "m-review": """\
---
title: Review the records
status: next
repos: [app]
branch: none
updated: 2026-09-15
next: "Read the oldest waiting record"
stage: build
---
""",
}


def main():
    if os.path.isdir(ROOT):
        shutil.rmtree(ROOT)
    dec = os.path.join(ROOT, "working-on", "decisions")
    os.makedirs(dec)
    os.makedirs(os.path.join(ROOT, "app"))
    with open(os.path.join(ROOT, "app", "README.md"), "w") as f:
        f.write("The many-records fixture's one repo.\n")
    with open(os.path.join(ROOT, "working-on", "initiative.yaml"), "w") as f:
        f.write(INITIATIVE)
    with open(os.path.join(ROOT, "working-on", "roadmap.yaml"), "w") as f:
        f.write(ROADMAP)
    for slug, body in CARDS.items():
        with open(os.path.join(ROOT, "working-on", slug + ".md"), "w") as f:
            f.write(body)
    for n in range(1, len(TOPICS) + 1):
        name, body = record(n)
        with open(os.path.join(dec, name), "w") as f:
            f.write(body)


if __name__ == "__main__":
    main()
