// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {discuss} from '../models';
import {service} from '../models';
import {auth} from '../models';
import {main} from '../models';
import {config} from '../models';

export function AddNote(arg1:string,arg2:string,arg3:string):Promise<model.Note>;

export function AttachSession(arg1:string):Promise<void>;

export function CellTypes():Promise<discuss.Thread|discuss.Message>;

export function Clean():Promise<service.RetireReport>;

export function ClearPasscode(arg1:string):Promise<service.LockState>;

export function ConfigPath():Promise<string>;

export function CopyReviewPrompt(arg1:string):Promise<void>;

export function CreateAgent(arg1:string,arg2:string):Promise<void>;

export function CreateCrew(arg1:string):Promise<Array<string>>;

export function EditNote(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetAccount():Promise<auth.Account>;

export function GetAgents():Promise<service.AgentsView>;

export function GetBoard():Promise<main.BoardView>;

export function GetCell(arg1:string):Promise<service.CellView>;

export function GetCellThread(arg1:string,arg2:string):Promise<service.CellThreadView>;

export function GetConfig():Promise<config.Config>;

export function GetLock():Promise<service.LockState>;

export function GetOrder():Promise<model.Order>;

export function KillAgent(arg1:string):Promise<void>;

export function LockNow():Promise<service.LockState>;

export function MilestoneType():Promise<model.Milestone>;

export function OpenInEditor(arg1:string):Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function PickUp(arg1:string):Promise<number>;

export function PlanRetire(arg1:service.RetireOptions):Promise<service.RetirePlan>;

export function PostToCell(arg1:string,arg2:service.CellPost):Promise<discuss.PostResult>;

export function ResetPassword(arg1:string):Promise<void>;

export function Retire(arg1:service.RetireOptions):Promise<service.RetireReport>;

export function Reveal(arg1:string):Promise<void>;

export function ReviewPrompt(arg1:string):Promise<string>;

export function RunReview(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SearchCell(arg1:string,arg2:string):Promise<Array<discuss.Message>>;

export function SetCardOrder(arg1:string,arg2:Array<string>):Promise<void>;

export function SetCellThreadStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetGroups(arg1:Array<model.Group>):Promise<void>;

export function SetInitiativeOrder(arg1:Array<string>):Promise<void>;

export function SetPasscode(arg1:string,arg2:string,arg3:boolean):Promise<service.LockState>;

export function SetResolved(arg1:string,arg2:boolean):Promise<void>;

export function SignIn(arg1:string,arg2:string):Promise<auth.Account>;

export function SignOut():Promise<void>;

export function SignUp(arg1:string,arg2:string):Promise<auth.Account>;

export function StopAgent(arg1:number):Promise<void>;

export function SyncNow():Promise<service.SyncResult>;

export function Unlock(arg1:string):Promise<service.LockState>;

export function Version():Promise<string>;
