// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddNote'](arg1, arg2, arg3);
}

export function AttachSession(arg1) {
  return window['go']['main']['App']['AttachSession'](arg1);
}

export function CellTypes() {
  return window['go']['main']['App']['CellTypes']();
}

export function Clean() {
  return window['go']['main']['App']['Clean']();
}

export function ClearPasscode(arg1) {
  return window['go']['main']['App']['ClearPasscode'](arg1);
}

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function CopyReviewPrompt(arg1) {
  return window['go']['main']['App']['CopyReviewPrompt'](arg1);
}

export function CreateAgent(arg1, arg2) {
  return window['go']['main']['App']['CreateAgent'](arg1, arg2);
}

export function CreateCrew(arg1) {
  return window['go']['main']['App']['CreateCrew'](arg1);
}

export function EditNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditNote'](arg1, arg2, arg3, arg4);
}

export function GetAccount() {
  return window['go']['main']['App']['GetAccount']();
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetBoard() {
  return window['go']['main']['App']['GetBoard']();
}

export function GetCell(arg1) {
  return window['go']['main']['App']['GetCell'](arg1);
}

export function GetCellThread(arg1, arg2) {
  return window['go']['main']['App']['GetCellThread'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLock() {
  return window['go']['main']['App']['GetLock']();
}

export function GetOrder() {
  return window['go']['main']['App']['GetOrder']();
}

export function KillAgent(arg1) {
  return window['go']['main']['App']['KillAgent'](arg1);
}

export function LockNow() {
  return window['go']['main']['App']['LockNow']();
}

export function MilestoneType() {
  return window['go']['main']['App']['MilestoneType']();
}

export function OpenInEditor(arg1) {
  return window['go']['main']['App']['OpenInEditor'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function PickUp(arg1) {
  return window['go']['main']['App']['PickUp'](arg1);
}

export function PlanRetire(arg1) {
  return window['go']['main']['App']['PlanRetire'](arg1);
}

export function PostToCell(arg1, arg2) {
  return window['go']['main']['App']['PostToCell'](arg1, arg2);
}

export function ResetPassword(arg1) {
  return window['go']['main']['App']['ResetPassword'](arg1);
}

export function Retire(arg1) {
  return window['go']['main']['App']['Retire'](arg1);
}

export function Reveal(arg1) {
  return window['go']['main']['App']['Reveal'](arg1);
}

export function ReviewPrompt(arg1) {
  return window['go']['main']['App']['ReviewPrompt'](arg1);
}

export function RunReview(arg1) {
  return window['go']['main']['App']['RunReview'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchCell(arg1, arg2) {
  return window['go']['main']['App']['SearchCell'](arg1, arg2);
}

export function SetCardOrder(arg1, arg2) {
  return window['go']['main']['App']['SetCardOrder'](arg1, arg2);
}

export function SetCellThreadStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCellThreadStatus'](arg1, arg2, arg3);
}

export function SetGroups(arg1) {
  return window['go']['main']['App']['SetGroups'](arg1);
}

export function SetInitiativeOrder(arg1) {
  return window['go']['main']['App']['SetInitiativeOrder'](arg1);
}

export function SetPasscode(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPasscode'](arg1, arg2, arg3);
}

export function SetResolved(arg1, arg2) {
  return window['go']['main']['App']['SetResolved'](arg1, arg2);
}

export function SignIn(arg1, arg2) {
  return window['go']['main']['App']['SignIn'](arg1, arg2);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}

export function SignUp(arg1, arg2) {
  return window['go']['main']['App']['SignUp'](arg1, arg2);
}

export function StopAgent(arg1) {
  return window['go']['main']['App']['StopAgent'](arg1);
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
