// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {auth} from '../models';
import {main} from '../models';
import {config} from '../models';
import {model} from '../models';

export function AttachSession(arg1:string):Promise<void>;

export function ClearPasscode(arg1:string):Promise<service.LockState>;

export function ConfigPath():Promise<string>;

export function CopyReviewPrompt(arg1:string):Promise<void>;

export function CreateAgent(arg1:string,arg2:string):Promise<void>;

export function GetAccount():Promise<auth.Account>;

export function GetAgents():Promise<service.AgentsView>;

export function GetBoard():Promise<main.BoardView>;

export function GetConfig():Promise<config.Config>;

export function GetLock():Promise<service.LockState>;

export function GetOrder():Promise<model.Order>;

export function KillAgent(arg1:string):Promise<void>;

export function LockNow():Promise<service.LockState>;

export function MilestoneType():Promise<model.Milestone>;

export function OpenInEditor(arg1:string):Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function ResetPassword(arg1:string):Promise<void>;

export function Reveal(arg1:string):Promise<void>;

export function ReviewPrompt(arg1:string):Promise<string>;

export function RunReview(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetCardOrder(arg1:string,arg2:Array<string>):Promise<void>;

export function SetInitiativeOrder(arg1:Array<string>):Promise<void>;

export function SetPasscode(arg1:string,arg2:string,arg3:boolean):Promise<service.LockState>;

export function SignIn(arg1:string,arg2:string):Promise<auth.Account>;

export function SignOut():Promise<void>;

export function SignUp(arg1:string,arg2:string):Promise<auth.Account>;

export function StopAgent(arg1:number):Promise<void>;

export function SyncNow():Promise<service.SyncResult>;

export function Unlock(arg1:string):Promise<service.LockState>;

export function Version():Promise<string>;
