// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachSession(arg1) {
  return window['go']['main']['App']['AttachSession'](arg1);
}

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function CopyReviewPrompt(arg1) {
  return window['go']['main']['App']['CopyReviewPrompt'](arg1);
}

export function CreateAgent(arg1, arg2) {
  return window['go']['main']['App']['CreateAgent'](arg1, arg2);
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetBoard() {
  return window['go']['main']['App']['GetBoard']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetOrder() {
  return window['go']['main']['App']['GetOrder']();
}

export function KillAgent(arg1) {
  return window['go']['main']['App']['KillAgent'](arg1);
}

export function MilestoneType() {
  return window['go']['main']['App']['MilestoneType']();
}

export function OpenInEditor(arg1) {
  return window['go']['main']['App']['OpenInEditor'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function Reveal(arg1) {
  return window['go']['main']['App']['Reveal'](arg1);
}

export function ReviewPrompt(arg1) {
  return window['go']['main']['App']['ReviewPrompt'](arg1);
}

export function RunReview(arg1) {
  return window['go']['main']['App']['RunReview'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetCardOrder(arg1, arg2) {
  return window['go']['main']['App']['SetCardOrder'](arg1, arg2);
}

export function SetInitiativeOrder(arg1) {
  return window['go']['main']['App']['SetInitiativeOrder'](arg1);
}

export function StopAgent(arg1) {
  return window['go']['main']['App']['StopAgent'](arg1);
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
